import { lastIndexOf } from "../index";
test('Check if lastIndexOf() works for Unicode strings', () => {
    expect(lastIndexOf('Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍🤣😒👌₦lizætiøn☃', '👌₦lizætiøn☃')).toBe(19);
    expect(lastIndexOf('Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍️🤣😒👌₦lizætiøn☃', 'æ', 0, -3)).toBe(24);
    expect(lastIndexOf('Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍️🤣😒👌₦lizætiøn☃', 't', 0, -3)).toBe(25);
    expect(lastIndexOf('Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍️🤣😒👌₦lizætiøn☃', 't')).toBe(25);
    expect(lastIndexOf('Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍🤣😒👌₦lizætiøn☃', 'Iñtërnâtiônà🏋️‍o✌🤷‍🤦‍', 0, 29)).toBe(0);
    expect(lastIndexOf('谢谢你', '谢谢你')).toBe(0);
    expect(lastIndexOf('谢谢你', '')).toBe(3);
    expect(lastIndexOf('谢谢你', '你')).toBe(2);
    expect(lastIndexOf('', '😎')).toBe(undefined);
    expect(lastIndexOf('', '')).toBe(0);
    expect(lastIndexOf('🎂🎂', '🙌⬅🛡😘🎂🎂🤣😒👌₦🎂🎂🎂🎂')).toBe(undefined);
    expect(lastIndexOf('🙌⬅🛡😘🎂🎂🤣😒👌₦🎂🎂🎂🎂', '🎂🎂')).toBe(12);
    expect(lastIndexOf('😍🎁😂🎉🎶🙌🕸👮🧔🍤🥟✈🛰💌💘', '✈🛰💌💘')).toBe(11);
    expect(lastIndexOf('😍🎁😂🎉🎶🙌🕸👮🧔🍤🥟✈🛰💌💘', '👮🧔🍤🥟')).toBe(7);
    expect(lastIndexOf('谢谢你', '谢谢你', 3, -1)).toBe(undefined);
    expect(lastIndexOf('谢谢你谢谢你', '谢谢你', 1, 6)).toBe(3);
    expect(lastIndexOf('谢谢你谢谢你', '谢谢你', 3, 6)).toBe(3);
    expect(lastIndexOf('谢谢你', '谢谢你', 0, 2)).toBe(undefined);
    expect(lastIndexOf('谢谢你谢谢你', '谢谢你', 0, 3)).toBe(0);
    expect(lastIndexOf('谢谢你谢谢你', '谢谢你', -10)).toBe(3);
    expect(lastIndexOf('👩‍👩‍👧‍👦', '👧‍')).toBe(undefined);
    expect(lastIndexOf('👩‍👩‍👧‍👦', '👩‍👩‍')).toBe(undefined);
});